server:
  port: 8890
  
spring:
  application:
    name: ms-admin-config-admin
  boot:
    admin:
      ui:
        title: "AMS - Core Tributario"
#        brand: "Core Tributario"
#        brand: "<img src='assets/img/logo.png' height='50px'/>"
#        #favicon: "assets/img/favicon.ico"  # Personaliza el icono
#        #login-icon: "static/login-icon.png"  # Imagen en la pantalla de login

